### ISSUE TITLE
請問哪裡可以找到 USB35INCHIPSV2 的串口指令集

### ISSUE THREAD

**Issue by apis-makerkang** [wanglvhang/PCMonitorForUSBScreen#1]
@wanglvhang 您好，我想使用 USB35INCHIPSV2，但找不到它的串口指令集，還請指點。

**Comment by wanglvhang** [comment]
这个接口的指令集是我通过它原来附带的软件反编译出来的，我问过商家他们不提供二次开发。所以你想知道的话目前只能通过自己反编译或者查看我的源代码。

从 Windows 版邮件发送

发件人: apis-makerkang
发送时间: 2023年3月15日 16:40
收件人: wanglvhang/PCMonitorForUSBScreen
抄送: leonwang; Mention
主题: [wanglvhang/PCMonitorForUSBScreen] 請問哪裡可以找到 USB35INCHIPSV2 的串口指令集 (Issue #1)

@wanglvhang 您好，我想使用 USB35INCHIPSV2，但找不到它的串口指令集，還請指點。

**Comment by apis-makerkang** [comment]
好的，謝謝你的答覆。
